### ISSUE TITLE
Deployment to GAE; pkg_resources.py fail to import

### ISSUE THREAD

**Issue by anirudhjoshi** [ThQ/p8ste#3]
The current version drops the following error for me when I deployed to my appspot.com subdomain.

<type 'exceptions.ImportError'>: No module named pkg_resources
Traceback (most recent call last):
  File "/base/data/home/apps/nazariuskappertaal/paste.341199620139568157/main.py", line 23, in <module>
    import page.pasties.add
  File "/base/data/home/apps/nazariuskappertaal/paste.341199620139568157/page/pasties/add/**init**.py", line 30, in <module>
    import recaptcha.client.captcha
  File "/base/data/home/apps/nazariuskappertaal/paste.341199620139568157/recaptcha/**init**.py", line 1, in <module>
    **import**('pkg_resources').declare_namespace(**name**)

Saw this on the app engine forums:
http://code.google.com/p/appengine-monkey/issues/detail?id=16
http://code.google.com/p/appengine-monkey/source/detail?r=59#

logger.notify('Copying pkg_resources.py')
222 +       import glob
223 +       filename = glob.glob(os.path.join(home_dir, 'lib/python2.5/site-packages/*/pkg_resources.py'))[0]
224 +       shutil.copy(filename, os.path.join(home_dir, 'app', 'lib', 'python', 'pkg_resources.py'))

**Comment by anirudhjoshi** [comment]
Resolved: deleted: **import**('pkg_resources').declare_namespace(**name**)
from src/recaptcha/**init**.py - unnecessary
