### ISSUE TITLE
Posting pasty on deployed instance; fails to post due to index

### ISSUE THREAD

**Issue by anirudhjoshi** [ThQ/p8ste#4]
Traceback (most recent call last):
  File "/base/python_lib/versions/1/google/appengine/ext/webapp/**init**.py", line 512, in **call**
    handler.post(_groups)
  File "/base/data/home/apps/nazariuskappertaal/paste.341201678007601008/page/pasties/add/**init**.py", line 427, in post
    self.on_load()
  File "/base/data/home/apps/nazariuskappertaal/paste.341201678007601008/page/pasties/add/**init**.py", line 293, in on_load
    self.on_form_sent()
  File "/base/data/home/apps/nazariuskappertaal/paste.341201678007601008/page/pasties/add/**init**.py", line 386, in on_form_sent
    if self.validate_form():
  File "/base/data/home/apps/nazariuskappertaal/paste.341201678007601008/page/pasties/add/**init**.py", line 449, in validate_form
    if result == True and not paste.form.has_valid_token(self.request.remote_addr, token):
  File "/base/data/home/apps/nazariuskappertaal/paste.341201678007601008/paste/form.py", line 36, in has_valid_token
    return tokens.get() != None
  File "/base/python_lib/versions/1/google/appengine/ext/db/**init**.py", line 1573, in get
    results = self.fetch(1, rpc=rpc)
  File "/base/python_lib/versions/1/google/appengine/ext/db/**init**.py", line 1626, in fetch
    raw = raw_query.Get(limit, offset, rpc=rpc)
  File "/base/python_lib/versions/1/google/appengine/api/datastore.py", line 1240, in Get
    limit=limit, offset=offset, prefetch_count=limit, *_kwargs)._Get(limit)
  File "/base/python_lib/versions/1/google/appengine/api/datastore.py", line 1175, in _Run
    str(exc) + '\nThis query needs this index:\n' + yaml)
NeedIndexError: no matching index found.
This query needs this index:
- kind: Form
  properties:
  - name: created_by_ip
  - name: token
  - name: expired_at

You also need to remove:
- kind: Pasty
  properties:
  - name: edited_at
    direction: desc
- kind: Pasty
  properties:
  - name: posted_at
    direction: desc

from index.yaml - appcfg says unnecessary

**Comment by ThQ** [comment]
Actually this index exists : http://github.com/thomas-quemard/p8ste/blob/master/src/index.yaml#L19

Maybe update your indexes : `python appcfg.py update_indexes /path/to/paste-it/src/`

Thanks for the needless indexes (how do you get appcfg to tell that ?)

**Comment by anirudhjoshi** [comment]
It does it automatically - with the latest linux SDK.

Odd, I pushed an index update last night and it didn't work - but now it does.
